version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: main

    ports:
      - "5432:5432"   # ← ВОТ ЭТО И ЕСТЬ ПРОБРОС ПОРТА

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
